deploy:
    authtoken: netify-auth-token
    siteid: netify site-id

gallery:
  name: "Gallery"
  imagesPerPage: 50
  basepath: "Photos"
  url:      "https://your.url.here"
  theme:    "default" #default uses embeded theme. change to path to use a differnt theme
  albumblacklist: [] # List if folder names to exclude from indexing
  pictureblacklist: [] # List of individule images to exclude 
  useoriginal: false # Include the orginal image in the publish site. 
  
about:
  enable: false
  photographer: "Joe Blogs"
  backgroundPhoto: "/img/galleryimagename"
  profilePhoto: "url to profile e.g gravatar"
  twitter: "@twitter"
  facebook: "facebook_username"
  instagram: "instagram_username"
  email: "me@example.com"
  blog: "https://blog.example.com"
  website: "https://example.com"
  description: "Hello there, here is my gallery containing a number of photos from a number of years"
  footer: "Photos ©photographer"