version: "2"

networks:
  gogallery:
    external: false

services:
  server:
    image: robrotheram/gogallery:latest
    restart: always
    networks:
      - gogallery
    volumes:
      - "./config.yml:/app/config.yml"
      - "/path/to/gallery:/app/pictures"
    ports:
       - "8085:8085"
    environment:
      GLLRY_GALLERY_BASEPATH: "/app/pictures"


