version: "2"

networks:
  gogallery:
    external: false

services:
  server:
    image: ghcr.io/robrotheram/gogallery:master
    restart: always
    networks:
      - gogallery
    volumes:
      - "./config.yml:/app/config.yml"
      - "/path/to/gallery:/app/pictures"
    ports:
       - 8085:80
    environment:
      GLLRY_GALLERY_BASEPATH: "/app/pictures"


